name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  DROPLET_NAME: music-guide
  IMAGE: abspayd/music-guide
  CONTAINER_NAME: music-guide
  VERSION: latest
  PORT: 3000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tailwindcss
        run: |
          npm install -D tailwindcss
          npm run publish
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: abspayd
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE }}:${{ env.VERSION }}
